version: "2"

services:
    frontend:
        build: .
        restart: always
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /tmp/letsencrypt-auto:/tmp/letsencrypt-auto
        ports:
            - "80:80"
            - "443:443"
